export const mockExperts = [
  {
    id: 'expert-1',
    email: 'sarah.johnson@example.com',
    name: 'Dr. Sarah Johnson',
    displayName: 'Dr. Sarah Johnson',
    userType: 'expert',
    bio: 'Clinical psychologist specializing in anxiety and stress management. Helping people find balance in their lives.',
    expertise: ['Psychology', 'Mental Health', 'Stress Management'],
    industry: 'Healthcare',
    yearsOfExperience: 12,
    chatRate: 60,
    callRate: 120,
    averageRating: 4.9,
    totalReviews: 87,
    totalSessions: 340,
    isOnline: true,
    photoURL: 'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'expert-2',
    email: 'michael.chen@example.com',
    name: 'Michael Chen',
    displayName: 'Michael Chen',
    userType: 'expert',
    bio: 'Senior software engineer and tech entrepreneur. Expert in web development, mobile apps, and startup strategy.',
    expertise: ['Software Development', 'Web Development', 'Mobile Apps', 'Startups'],
    industry: 'Technology',
    yearsOfExperience: 15,
    chatRate: 80,
    callRate: 150,
    averageRating: 4.8,
    totalReviews: 124,
    totalSessions: 520,
    isOnline: false,
    photoURL: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'expert-3',
    email: 'emily.rodriguez@example.com',
    name: 'Emily Rodriguez',
    displayName: 'Emily Rodriguez',
    userType: 'expert',
    bio: 'Marketing strategist with a passion for brand building and digital marketing. Let me help grow your business.',
    expertise: ['Marketing', 'Branding', 'Digital Marketing', 'Social Media'],
    industry: 'Marketing',
    yearsOfExperience: 8,
    chatRate: 55,
    callRate: 100,
    averageRating: 4.7,
    totalReviews: 63,
    totalSessions: 210,
    isOnline: true,
    photoURL: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'expert-4',
    email: 'david.kim@example.com',
    name: 'David Kim',
    displayName: 'David Kim',
    userType: 'expert',
    bio: 'Financial advisor and investment strategist. Helping individuals and businesses achieve their financial goals.',
    expertise: ['Finance', 'Investment', 'Retirement Planning', 'Wealth Management'],
    industry: 'Finance',
    yearsOfExperience: 20,
    chatRate: 90,
    callRate: 180,
    averageRating: 4.9,
    totalReviews: 156,
    totalSessions: 680,
    isOnline: true,
    photoURL: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'expert-5',
    email: 'lisa.anderson@example.com',
    name: 'Lisa Anderson',
    displayName: 'Lisa Anderson',
    userType: 'expert',
    bio: 'Career coach and HR professional. I guide professionals through career transitions and help them reach their potential.',
    expertise: ['Career Coaching', 'HR', 'Leadership', 'Professional Development'],
    industry: 'Human Resources',
    yearsOfExperience: 10,
    chatRate: 65,
    callRate: 125,
    averageRating: 4.8,
    totalReviews: 92,
    totalSessions: 380,
    isOnline: false,
    photoURL: 'https://images.pexels.com/photos/3756679/pexels-photo-3756679.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'expert-6',
    email: 'james.thompson@example.com',
    name: 'James Thompson',
    displayName: 'James Thompson',
    userType: 'expert',
    bio: 'Business consultant specializing in operations and process improvement. Let me help streamline your business.',
    expertise: ['Business Strategy', 'Operations', 'Process Improvement', 'Management'],
    industry: 'Business Consulting',
    yearsOfExperience: 18,
    chatRate: 75,
    callRate: 140,
    averageRating: 4.7,
    totalReviews: 110,
    totalSessions: 450,
    isOnline: true,
    photoURL: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];

export const mockReviews = [
  {
    id: 'review-1',
    expertId: 'expert-1',
    clientId: 'client-1',
    clientName: 'Alice Brown',
    rating: 5,
    comment: 'Dr. Johnson was incredibly helpful! Her advice on managing work stress has been life-changing.',
    createdAt: new Date('2024-11-20'),
  },
  {
    id: 'review-2',
    expertId: 'expert-1',
    clientId: 'client-2',
    clientName: 'Robert Green',
    rating: 5,
    comment: 'Excellent session. Very professional and understanding. Highly recommend!',
    createdAt: new Date('2024-11-18'),
  },
  {
    id: 'review-3',
    expertId: 'expert-2',
    clientId: 'client-3',
    clientName: 'Sophie Miller',
    rating: 5,
    comment: 'Michael helped me launch my startup successfully. His technical expertise is outstanding.',
    createdAt: new Date('2024-11-22'),
  },
];

export const mockMessages = [
  {
    id: 'msg-1',
    senderId: 'expert-1',
    receiverId: 'mock-user-123',
    content: 'Hi! How can I help you today?',
    createdAt: new Date('2024-11-28T10:00:00'),
  },
  {
    id: 'msg-2',
    senderId: 'mock-user-123',
    receiverId: 'expert-1',
    content: 'I need some advice on managing work stress.',
    createdAt: new Date('2024-11-28T10:02:00'),
  },
  {
    id: 'msg-3',
    senderId: 'expert-1',
    receiverId: 'mock-user-123',
    content: 'I understand. Let me share some effective techniques that can help you...',
    createdAt: new Date('2024-11-28T10:03:00'),
  },
];

export const mockSessions = [
  {
    id: 'session-1',
    expertId: 'expert-1',
    clientId: 'mock-user-123',
    sessionType: 'chat',
    status: 'completed',
    ratePerMinute: 60,
    durationMinutes: 30,
    totalCost: 1800,
    createdAt: new Date('2024-11-20'),
  },
  {
    id: 'session-2',
    expertId: 'expert-2',
    clientId: 'mock-user-123',
    sessionType: 'call',
    status: 'completed',
    ratePerMinute: 150,
    durationMinutes: 45,
    totalCost: 6750,
    createdAt: new Date('2024-11-15'),
  },
];
